disquaire_project/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from django.conf import settings

from store import views


urlpatterns = [
    url(r'^$', views.index),
    url(r'^store/', include(('store.urls', 'store'), namespace='store')),
    url(r'^admin/', admin.site.urls)

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [

        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

store/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^albums/$', views.albums, name="listing"),
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^search/', views.search, name="search")
]

store/models.py
from django.db import models

# Create your models here.
class Artist(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

class Contact(models.Model):

    def __str__(self):
        return self.name

    email = models.EmailField(max_length=100)
    name = models.CharField(max_length=200)



class Album(models.Model):

    def __str__(self):
        return self.title

    reference = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    available = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    picture = models.URLField()
    artists = models.ManyToManyField(Artist, related_name="albums", blank=True)


class Booking(models.Model):

    def __str__(self):
        return self.contact.name

    created_at = models.DateTimeField(auto_now_add = True)
    contacted = models.BooleanField(default=False)
    album = models.OneToOneField(Album, on_delete=models.CASCADE)
    contact = models.ForeignKey(Contact, on_delete = models.CASCADE)

store/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from .models import Album, Artist, Contact, Booking

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage


# Create your views here.
def index(request): # Displays latest albums

    albums = Album.objects.filter(available=True).order_by('-created_at')[:12]
    context = {
        "albums": albums,
        "page_title": "Nos derniers albums"
   }

    return render(request, "store/index.html", context)

def albums(request): # Displays all albums

    album_list = Album.objects.filter(available=True)

    page = request.GET.get('page')

    paginator = Paginator(album_list, 3)

    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        albums = paginator.page(1)
    except EmptyPage:
        albums = paginator.page(paginator.num_pages)

    context = {
        "albums": albums,
        "page_title": "Tous nos albums",
        "paginate": True
        }

    return render(request, "store/listing.html", context)

def detail(request, album_id):

    album = get_object_or_404(Album, pk=album_id)
    artists = " ".join(artist.name for artist in album.artists.all())

    context = {
        "album": album,
        "artists":artists
    }
    return render(request, "store/detail.html", context)

def search(request):
    query = request.GET.get('query')
    message = ""

    if not query:
        albums = Album.objects.all()
    else:
        albums = Album.objects.filter(title__icontains=query)

        if not albums.exists():
            albums = Album.objects.filter(artists__name__icontains=query)

    context = {
        "query": query,
        "albums": albums
    }

    return render(request, "store/search.html", context)

disquaire_project/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-casual.css" rel="stylesheet">

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Business Casual</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="index.html">Home</a>
                    </li>
                    <li>
                        <a href="about.html">About</a>
                    </li>
                    <li>
                        <a href="blog.html">Blog</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                <div class="col-lg-12 text-center">
                    <div id="carousel-example-generic" class="carousel slide">
                        <!-- Indicators -->
                        <ol class="carousel-indicators hidden-xs">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="img-responsive img-full" src="img/slide-1.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-2.jpg" alt="">
                            </div>
                            <div class="item">
                                <img class="img-responsive img-full" src="img/slide-3.jpg" alt="">
                            </div>
                        </div>

                        <!-- Controls -->
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="icon-prev"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="icon-next"></span>
                        </a>
                    </div>
                    <h2 class="brand-before">
                        <small>Welcome to</small>
                    </h2>
                    <h1 class="brand-name">Business Casual</h1>
                    <hr class="tagline-divider">
                    <h2>
                        <small>By
                            <strong>Start Bootstrap</strong>
                        </small>
                    </h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Build a website
                        <strong>worth visiting</strong>
                    </h2>
                    <hr>
                    <img class="img-responsive img-border img-left" src="img/intro-pic.jpg" alt="">
                    <hr class="visible-xs">
                    <p>The boxes used in this template are nested inbetween a normal Bootstrap row and the start of your column layout. The boxes will be full-width boxes, so if you want to make them smaller then you will need to customize.</p>
                    <p>A huge thanks to <a href="http://join.deathtothestockphoto.com/" target="_blank">Death to the Stock Photo</a> for allowing us to use the beautiful photos that make this template really come to life. When using this template, make sure your photos are decent. Also make sure that the file size on your photos is kept to a minumum to keep load times to a minimum.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="box">
                <div class="col-lg-12">
                    <hr>
                    <h2 class="intro-text text-center">Beautiful boxes
                        <strong>to showcase your content</strong>
                    </h2>
                    <hr>
                    <p>Use as many boxes as you like, and put anything you want in them! They are great for just about anything, the sky's the limit!</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>
                </div>
            </div>
        </div>

    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

store/templates/store/base.html
<!DOCTYPE html>

{%load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Casual - Start Bootstrap Theme</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'store/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'store/css/business-casual.css' %}" rel="stylesheet">
    <link href="{% static 'store/css/custom.css' %}" rel="stylesheet"  />

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div class="brand">Le bateau pirate</div>
    <div class="address-bar">3481 Melrose Place | Beverly Hills, CA 90210 | 123.456.7890</div>

    <!-- Navigation -->
    <nav class="navbar navbar-default" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- navbar-brand is hidden on larger screens, but visible when the menu is collapsed -->
                <a class="navbar-brand" href="index.html">Business Casual</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="/">Accueil</a>
                    </li>
                    <li>
                        <a href="{% url 'store:listing' %}">Liste des albums</a>
                    </li>
                    <li>
                        <a href="blog.html">Blog</a>
                    </li>
                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <div class="container">

        <div class="row">
            <div class="box">
                {% block content %}{% endblock %}
            </div>
        </div>



    </div>
    <!-- /.container -->

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'store/js/jquery.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'store/js/bootstrap.min.js' %}"></script>

    <!-- Script to Activate the Carousel -->
    <script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
    </script>

</body>

</html>

store/templates/store/detail.html
{% extends 'store/base.html' %}


{% block content %}
    <h2 class="text-center">Présentation de l'album</h2>

    <div class='col-md-6 img-album'>
      <img class="img-responsive" src="{{album.picture}}"/>
    </div>
    <div clss="col-md-6 infos-album">
      <p>
        Nom de l'album : <span class="nom_album">{{album.title}}</span>
      </p>
      <p>
        Artistes : <span> {{ artists }}</span>
      </p>

      <p>
        Disponible : <span>{{album.available}}</span>
      </p>


    </div>





{% endblock %}

store/templates/store/index.html
{% extends 'store/base.html' %}

{% block content %}
  {% include 'store/list.html' %}
{% endblock %}

store/templates/store/list.html
<h2 class=" intro-text text-center">{{ page_title }}</h2>

{% include 'store/search_form.html' %}
<ul>

  {% for album in albums %}
  <div class="col-sm-4 text-center">
      <a href="{% url 'store:detail' album_id=album.id%}">
        <img class="img-responsive img-albums" src="{{album.picture}}" alt="{{album.title}}"  />
      </a>

      <h3><a href="{% url 'store:detail' album_id=album.id%}">{{album.title}}</a></h3>

      {% for artist in album.artists.all %}
        <p>
          {{artist.name}}
        </p>

        {% endfor %}
  </div>


    {% if forloop.counter|divisibleby:3 %}<div class="clearfix"></div>{% endif %}

{% endfor %}

</ul>
<div class="clearfix">

</div>
{% if paginate %}
<nav aria-label="">
  <ul class="pager">
    {% if albums.has_previous %}
      <li>
        <a href="?page={{albums.previous_page_number }}">Précédent</a>
      </li>
    {% endif %}
    {% if albums.has_next %}
      <li>
        <a href="?page={{albums.next_page_number }}">Suivant</a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

store/templates/store/listing.html
{% extends 'store/base.html' %}


{% block content %}
  {% include 'store/list.html' %}
{% endblock %}

store/templates/store/search.html
{% extends 'store/base.html' %}


{% block content %}

  {% if albums|length_is:"0" %}
    <p>
      Palsambleu ! Nous avons un problème !
    </p>


  {% else %}
      {% include 'store/list.html' with page_title="Résultats" %}
  {% endif %}
{% endblock %}

store/templates/store/search_form.html
<div class="col-lg-12 detail-separator">
  <form class="col-md-6 col-md-offset-3 text-center" action="{% url 'store:search' %}" method="get" accept-charset="utf-8">
    <div class="form-group">
      <label for="searchForm">Chercher un disque</label>
      <input id="searchForm" class="form-control" name="query">
    </div>
    <span class="help-block" id="helpBlock">Trouvez le CD de vos rêves en tapant son titre ou le nom d'un des artistes.</span>
  </form>
</div>